### ISSUE TITLE
By 6/15: Change virtual bins to ASILE01-ASILE20 based on handler. Should actually simplify the code.

### ISSUE THREAD

**Issue by TimothyElbert** [WolfByteLabs/slotmachine_app#8]
Using real slots may be confusing and not necessary, since both admins and handlers look to that list for guidance. They will create an actual set of virtual bins called ASILE01 to ASILE20 to be used to stash something. This way it actually corresponds to the physical moves that the movers have to make. If we want to be really nice, although Bruce didn't ask for this, next to AISLE01 we should put in parenthesis the final destination for the mover to save them one extra length of that swap.

**Comment by mjwolfbyte** [comment]
Updated diff functionality and pushed to production.

https://sams-slotmachine.azurewebsites.net/api/display_diff?handlers=5
